"""
AgentLens — Live Demo
=====================
Simulates a real-world NBFC credit decisioning workflow using a
LangChain-style agent, instrumented with AgentLens for full
RBI FREE-AI + MRM 2026 compliance.

This demo deliberately avoids calling real LLM APIs so it runs
completely offline. The audit architecture is identical to
production — swap the mock for a real LangChain agent and it works.

Run:
    python examples/demo_credit_agent.py
"""

import sys
import os
import json
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from agentlens import (
    AuditTracer,
    AgentLensConfig,
    ComplianceReporter,
    PolicyEngine,
    RBIPolicy,
    SEBIPolicy,
)
from agentlens.config import EntityType, RegulatoryFramework
from agentlens.audit_log import RiskTier
from agentlens.policy import PolicyAction

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table
    from rich.syntax import Syntax
    from rich import print as rprint
    RICH = True
    console = Console()
except ImportError:
    RICH = False
    console = None


def section(title: str):
    if RICH:
        console.rule(f"[bold cyan]{title}[/bold cyan]")
    else:
        print(f"\n{'='*60}\n  {title}\n{'='*60}")


def info(msg: str):
    if RICH:
        console.print(f"[green]✓[/green] {msg}")
    else:
        print(f"  ✓ {msg}")


def warn(msg: str):
    if RICH:
        console.print(f"[yellow]⚠[/yellow]  {msg}")
    else:
        print(f"  ⚠ {msg}")


def error(msg: str):
    if RICH:
        console.print(f"[red]✗[/red] {msg}")
    else:
        print(f"  ✗ {msg}")


# ─────────────────────────────────────────────────────────────────────────────
# Mock LangChain-style agent (replace with real agent in production)
# ─────────────────────────────────────────────────────────────────────────────

class MockCreditDecisioningAgent:
    """
    Simulates a credit decisioning AI agent at an NBFC.
    In production: replace with LangChain ReAct agent, CrewAI, or AutoGen.
    The AgentLens instrumentation is identical regardless of the framework.
    """
    name = "credit_decisioning_agent_v2"
    version = "2.1.4"
    model = "llama-3.1-70b-instruct"          # e.g. India-deployed sovereign model

    def fetch_cibil_score(self, applicant_id_hash: str) -> dict:
        """Mock CIBIL bureau call."""
        time.sleep(0.05)  # Simulate API latency
        return {"score": 724, "accounts": 3, "dpd_30": 0}

    def fetch_income_data(self, applicant_id_hash: str) -> dict:
        """Mock bank statement / GST data fetch."""
        time.sleep(0.03)
        return {"monthly_income_inr": 85000, "source": "bank_statement_gst"}

    def compute_credit_decision(self, cibil: dict, income: dict, loan_amount: int) -> dict:
        """
        Deterministic credit rule engine (not black-box LLM).
        In production this can be LLM-assisted but the POLICY CHECK
        and WHY-TRAIL are always generated by AgentLens independently.
        """
        emi = loan_amount / 24
        dscr = income["monthly_income_inr"] / emi  # Debt service coverage ratio
        approved = cibil["score"] >= 700 and dscr >= 2.5 and cibil["dpd_30"] == 0

        return {
            "approved": approved,
            "cibil_score": cibil["score"],
            "dscr": round(dscr, 2),
            "emi_inr": round(emi),
            "rule_checks": {
                "cibil_pass": cibil["score"] >= 700,
                "dscr_pass": dscr >= 2.5,
                "dpd_pass": cibil["dpd_30"] == 0,
            },
        }


# ─────────────────────────────────────────────────────────────────────────────
# DEMO
# ─────────────────────────────────────────────────────────────────────────────

def run_demo():
    if RICH:
        console.print(Panel.fit(
            "[bold white]AgentLens SDK — Live Demo[/bold white]\n"
            "[dim]RBI FREE-AI + MRM 2026 Compliance-Grade Audit[/dim]\n"
            "[dim]NBFC Credit Decisioning Agent[/dim]",
            border_style="cyan"
        ))
    else:
        print("\n" + "="*60)
        print("  AgentLens SDK — Live Demo")
        print("  RBI FREE-AI + MRM 2026 Compliance-Grade Audit")
        print("  NBFC Credit Decisioning Agent")
        print("="*60)

    # ── STEP 1: Configure AgentLens for this NBFC ────────────────────────────
    section("STEP 1 — Configure AgentLens for Regulated Entity")

    config = AgentLensConfig(
        entity_name="ArogyaFinance NBFC Ltd.",
        entity_type=EntityType.NBFC,
        regulatory_frameworks=[
            RegulatoryFramework.RBI_FREE_AI,
            RegulatoryFramework.RBI_MRM_2026,
            RegulatoryFramework.DPDP_2023,
        ],
        board_policy_ref="AI_GOVERNANCE_POLICY_v1.2_BOARD_MAR2026",
        audit_retention_days=1825,    # RBI: 5 year minimum
        pii_masking_enabled=True,
        default_model_risk_tier=1,    # Tier 1 = Credit decisions (highest scrutiny)
    )

    info(f"Entity: {config.entity_name} ({config.entity_type.value})")
    info(f"Board policy: {config.board_policy_ref}")
    info(f"Frameworks: {[f.value for f in config.regulatory_frameworks]}")
    info(f"Audit retention: {config.audit_retention_days} days (RBI: 5 yrs)")
    info(f"PII masking: {'ON' if config.pii_masking_enabled else 'OFF'}")

    # ── STEP 2: Configure Policy Engine with RBI rules ───────────────────────
    section("STEP 2 — Load RBI FREE-AI Policy Rules")

    engine = PolicyEngine()
    credit_rules = RBIPolicy.credit_decision_rules()
    engine.add_rules(credit_rules)

    if RICH:
        t = Table(title="Loaded Policy Rules", show_lines=True)
        t.add_column("Rule ID", style="cyan")
        t.add_column("Description")
        t.add_column("Regulatory Ref", style="dim")
        t.add_column("Action on Fail", style="yellow")
        for r in credit_rules:
            t.add_row(r.rule_id, r.description, r.regulatory_ref, r.action_on_fail.value.upper())
        console.print(t)
    else:
        for r in credit_rules:
            print(f"  [{r.rule_id}] {r.description} → {r.action_on_fail.value.upper()}")

    # ── STEP 3: Run the agent with full audit tracing ────────────────────────
    section("STEP 3 — Run Credit Agent with AgentLens Instrumentation")

    tracer = AuditTracer(config=config, policy_engine=engine)
    agent = MockCreditDecisioningAgent()

    # Simulate loan application
    LOAN_AMOUNT_INR = 500_000   # ₹5 lakh personal loan
    APPLICANT_ID = "CUST_8842991"   # Never stored in plain text

    import hashlib
    applicant_hash = hashlib.sha256(APPLICANT_ID.encode()).hexdigest()[:16]
    info(f"Processing loan application: ₹{LOAN_AMOUNT_INR:,}")
    info(f"Applicant ID (hashed for DPDP): {applicant_hash}...")

    with tracer.trace_agent(agent.name) as span:

        span.set_model(agent.model, "2025-Q3")
        span.set_risk_tier(RiskTier.HIGH)              # Tier 1 — credit decision
        span.set_agent_version(agent.version)
        span.set_policy("CREDIT_POLICY_v3.2_APR2026")

        info("Agent started. Fetching bureau data...")

        # Tool call 1: CIBIL bureau
        t0 = time.time()
        cibil = agent.fetch_cibil_score(applicant_hash)
        span.record_tool_call(
            tool_name="cibil_bureau_api",
            params={"applicant_hash": applicant_hash, "bureau": "TransUnion_CIBIL"},
            result=cibil,
            latency_ms=int((time.time() - t0) * 1000),
        )
        info(f"CIBIL score fetched: {cibil['score']} (logged, params hashed)")

        # Tool call 2: Income verification
        t0 = time.time()
        income = agent.fetch_income_data(applicant_hash)
        span.record_tool_call(
            tool_name="income_verification_api",
            params={"applicant_hash": applicant_hash, "source": "gst_bank_statement"},
            result=income,
            latency_ms=int((time.time() - t0) * 1000),
        )
        info(f"Income verified: ₹{income['monthly_income_inr']:,}/month")

        # Compute decision
        decision = agent.compute_credit_decision(cibil, income, LOAN_AMOUNT_INR)
        status = "APPROVED" if decision["approved"] else "REJECTED"

        # Build human-readable reasoning (independent of LLM output)
        reasoning = (
            f"Loan {status} — ₹{LOAN_AMOUNT_INR:,} Personal Loan. "
            f"CIBIL: {decision['cibil_score']} (≥700: {'PASS' if decision['rule_checks']['cibil_pass'] else 'FAIL'}). "
            f"DSCR: {decision['dscr']}x (≥2.5x: {'PASS' if decision['rule_checks']['dscr_pass'] else 'FAIL'}). "
            f"30-day DPD: {'PASS' if decision['rule_checks']['dpd_pass'] else 'FAIL'}. "
            f"Policy ref: CREDIT_POLICY_v3.2_APR2026, Section 4.2."
        )

        # Record decision + run policy engine
        span.record_decision(
            output=f"{status}: ₹{LOAN_AMOUNT_INR:,} loan at 12.5% for 24 months. EMI ₹{decision['emi_inr']:,}",
            reasoning=reasoning,
            context={
                "decision_amount_inr": LOAN_AMOUNT_INR,
                "human_review_requested": LOAN_AMOUNT_INR > 1_000_000,
                "pii_masked": True,
            },
        )

        if decision["approved"]:
            info(f"Decision: ✅ {status}")
        else:
            warn(f"Decision: ❌ {status}")
        info(f"Reasoning logged: {reasoning[:80]}...")

    # ── STEP 4: Show audit trail ─────────────────────────────────────────────
    section("STEP 4 — Audit Trail (Tamper-Evident Chain)")

    audit_log = tracer.get_log()
    summary = audit_log.summary()

    if RICH:
        t = Table(title="Audit Events", show_lines=True)
        t.add_column("#", style="dim", width=4)
        t.add_column("Event Type", style="cyan")
        t.add_column("Agent")
        t.add_column("Tool / Decision")
        t.add_column("Hash (first 12)", style="dim")
        for i, e in enumerate(audit_log.get_events(), 1):
            detail = e.tool_name or (e.decision_output[:40] if e.decision_output else "") or ""
            t.add_row(
                str(i), e.event_type.value, e.agent_id[:20],
                detail[:40], e.event_hash[:12] + "..."
            )
        console.print(t)
    else:
        for i, e in enumerate(audit_log.get_events(), 1):
            detail = e.tool_name or (e.decision_output[:30] if e.decision_output else "")
            print(f"  [{i}] {e.event_type.value:30s} | {detail[:30]:30s} | {e.event_hash[:12]}...")

    info(f"Chain integrity: {'✅ VERIFIED' if summary['chain_intact'] else '⚠ BROKEN'}")
    info(f"Total events: {summary['total_events']}")

    # ── STEP 5: Policy why-trail ─────────────────────────────────────────────
    section("STEP 5 — Policy Why-Trail (RBI FREE-AI Rec 18 Explainability)")

    span_result = audit_log.get_events()
    decision_event = next(
        (e for e in reversed(span_result) if e.event_type.value == "agent.decision"), None
    )

    policy_result = tracer.audit_log  # Access through the engine
    # Re-evaluate for display
    ctx = {
        "decision_amount_inr": LOAN_AMOUNT_INR,
        "human_review_requested": False,
        "pii_masked": True,
        "policy_ref": "CREDIT_POLICY_v3.2_APR2026",
        "human_readable_reasoning": reasoning,
    }
    policy_eval = engine.evaluate(ctx, risk_tier=1)

    if RICH:
        t = Table(title="Policy Why-Trail — Independent of LLM Chain-of-Thought", show_lines=True)
        t.add_column("Rule", style="cyan", width=18)
        t.add_column("Regulatory Ref", style="dim", width=30)
        t.add_column("Result", width=10)
        t.add_column("Evidence / Reason")
        for entry in policy_eval.why_trail:
            result_str = "[green]PASS[/green]" if entry["passed"] else f"[red]{entry['action_on_fail'].upper()}[/red]"
            t.add_row(
                entry["rule_id"], entry["regulatory_ref"][:30],
                result_str, entry["reason"][:60]
            )
        console.print(t)
        console.print(f"\nOverall policy decision: [bold]{'✅ ALLOW' if policy_eval.overall_action == PolicyAction.ALLOW else '⚠ ' + policy_eval.overall_action.value.upper()}[/bold]")
    else:
        for entry in policy_eval.why_trail:
            status_str = "PASS" if entry["passed"] else entry["action_on_fail"].upper()
            print(f"  [{status_str:8s}] {entry['rule_id']:20s} | {entry['reason'][:60]}")
        print(f"\n  Overall: {policy_eval.overall_action.value.upper()}")

    # ── STEP 6: Compliance Report ────────────────────────────────────────────
    section("STEP 6 — RBI FREE-AI Compliance Report (Board-Ready)")

    reporter = ComplianceReporter(audit_log, config)
    print(reporter.executive_dashboard())

    # ── STEP 7: JSON Export ──────────────────────────────────────────────────
    section("STEP 7 — Full Audit Export (JSON)")

    export = tracer.export_audit_report(format="json")
    export_path = "/tmp/agentlens_audit_demo.json"
    with open(export_path, "w") as f:
        f.write(export)
    info(f"Full audit trail exported to: {export_path}")
    info(f"Format: JSON — ready for SIEM ingestion, RBI examiner submission, or Big 4 audit review")

    # Show a snippet
    data = json.loads(export)
    snippet = json.dumps({
        "agentlens_version": data["agentlens_version"],
        "entity": data["entity"],
        "chain_verified": data["chain_verified"],
        "audit_summary": data["audit_summary"],
    }, indent=2)

    if RICH:
        console.print(Syntax(snippet, "json", theme="monokai", line_numbers=False))
    else:
        print(snippet)

    if RICH:
        console.print(Panel.fit(
            "[bold green]Demo complete.[/bold green]\n\n"
            "AgentLens has:\n"
            "  ✅ Wrapped a credit decisioning agent\n"
            "  ✅ Logged all tool calls (params hashed — DPDP compliant)\n"
            "  ✅ Generated a policy why-trail (independent of LLM)\n"
            "  ✅ Verified tamper-evident chain integrity\n"
            "  ✅ Produced board-ready RBI FREE-AI compliance report\n"
            "  ✅ Exported regulator-ready JSON audit trail\n\n"
            "[dim]Works with any agent framework. No lock-in.[/dim]",
            border_style="green"
        ))
    else:
        print("\n" + "="*60)
        print("  Demo complete.")
        print("  AgentLens wrapped a credit decisioning agent with full")
        print("  RBI FREE-AI + MRM 2026 compliant audit trail.")
        print("="*60)


if __name__ == "__main__":
    run_demo()
